language: java
install: echo
script: mvn clean install site
jdk:
- openjdk7
env:
  secure: "LWbUPi5WUGjBxDzZCtuUkUSB8232mN6N3mJc6l4qvco2L9pQsHJT8/DF4IZjW+hRVvS1gn7EIVEOIW1Qq1KzglRcWLCK9kHqH15PEXn9Qnn5zLJUQMiICzL6+h40G/nQfrh5VYJt7jEvBoqYruWTmdiVa4GfESQ0DePtQPncNbU="