language: java
before_install: "curl https://raw.githubusercontent.com/meles-software/meles-maven-settings/0.1/settings.xml > settings.xml"
install: true
script: mvn clean deploy --settings settings.xml
after_script:
- mvn site -Dgithub.global.oauth2Token=${GITHUB_TOKEN}
jdk:
- openjdk7
env:
  secure: YnRPDfRYhPd1FYg+WRQiTeidrHOuSAlGniwBZzcEyO7FQKo132zi30fivLMPto6YvLmZSAeBLJve+ietiwC4dCv/4fRKL4t8j7sWg6JkJ9D8OVOlhOb1s8jcH/56ud29VVkYTFn4RQuLCRBcZOma5IYmvEubLuZZClV0010aoMY=
branches:
  except:
    - travis-settings