language: java
install: echo ${A_KEY}
script: mvn clean install site -Dgithub.global.oauth2Token=${GITHUB_TOKEN}
jdk:
- openjdk7
env:
  secure: "LWbUPi5WUGjBxDzZCtuUkUSB8232mN6N3mJc6l4qvco2L9pQsHJT8/DF4IZjW+hRVvS1gn7EIVEOIW1Qq1KzglRcWLCK9kHqH15PEXn9Qnn5zLJUQMiICzL6+h40G/nQfrh5VYJt7jEvBoqYruWTmdiVa4GfESQ0DePtQPncNbU="
  secure: "P3JhJnc+UohE1r7/m4iWY1m72JMnLu2DdzVsDd8rLG01tYAl8tdePTjRyq8nfcBs6x+5fXtcq5CwG9cC15LbUCy38RdKogduK2VMBtQqsa+uFmz+NLHasNCn3Y/kPiFwZoq6wiIffU8F+FZRZ8wqvkV09ejxi8HH+86MmF3ozhI="
